# Generated by Django 5.2.4 on 2025-08-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location_input", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dnogroup",
            name="abbreviation",
        ),
        migrations.AddField(
            model_name="dnogroup",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
