# Generated by Django 5.2.4 on 2025-08-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location_input", "0009_gspsubstation_voltage_kv"),
    ]

    operations = [
        migrations.AddField(
            model_name="bspsubstation",
            name="voltage_kv",
            field=models.ManyToManyField(
                blank=True,
                related_name="bsp_substations",
                to="location_input.connectionvoltagelevel",
            ),
        ),
        migrations.AddField(
            model_name="primarysubstation",
            name="voltage_kv",
            field=models.ManyToManyField(
                blank=True,
                related_name="primary_substations",
                to="location_input.connectionvoltagelevel",
            ),
        ),
    ]
