# Generated by Django 5.2.4 on 2025-08-02 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location_input", "0010_bspsubstation_voltage_kv_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProposedConnectionVoltageLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level_kv",
                    models.DecimalField(
                        choices=[
                            (6.6, "6.6 kV"),
                            (11.0, "11 kV"),
                            (33.0, "33 kV"),
                            (66.0, "66 kV"),
                            (132.0, "132 kV"),
                        ],
                        decimal_places=1,
                        max_digits=5,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="newconnection",
            name="voltage_level",
        ),
        migrations.AddField(
            model_name="newconnection",
            name="connection_voltage_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="new_connections",
                to="location_input.proposedconnectionvoltagelevel",
            ),
        ),
    ]
