# Generated by Django 5.2.4 on 2025-08-03 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location_input", "0013_alter_proposedconnectionvoltagelevel_level_kv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newconnection",
            name="connection_voltage_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="new_connections",
                to="location_input.connectionvoltagelevel",
            ),
        ),
        migrations.DeleteModel(
            name="ProposedConnectionVoltageLevel",
        ),
    ]
