# Generated by Django 5.2.4 on 2025-08-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location_input", "0017_remove_newconnection_bsp_substation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="substation",
            name="external_identifier",
            field=models.CharField(
                default="default_substation", max_length=255, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="connectionstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("budget", "Budget Estimate Provided"),
                    ("pending", "Connection Offer – Pending Acceptance"),
                    ("accepted", "Connection Offer – Accepted"),
                ],
                max_length=100,
            ),
        ),
    ]
