# Generated by Django 5.2.4 on 2025-08-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location_input", "0020_alter_substation_external_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="substation",
            name="external_identifier",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
