# Generated by Django 5.2.4 on 2025-08-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location_input", "0021_alter_substation_external_identifier"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="substation",
            constraint=models.UniqueConstraint(
                fields=("dno_group", "external_identifier"),
                name="unique_dno_group_external_identifier",
            ),
        ),
    ]
