# Generated by Django 5.2.4 on 2025-08-01 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_dnogroup_name_dnogroup_abbr"),
    ]

    operations = [
        migrations.AddField(
            model_name="newconnection",
            name="dno_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="new_connections",
                to="core.dnogroup",
            ),
        ),
    ]
