# Generated by Django 5.2.4 on 2025-08-02 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_bspsubstation_voltage_kv_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="primarysubstation",
            name="voltage_kv",
        ),
        migrations.RemoveField(
            model_name="bspsubstation",
            name="voltage_kv",
        ),
        migrations.RemoveField(
            model_name="gspsubstation",
            name="voltage_kv",
        ),
        migrations.DeleteModel(
            name="SubstationVoltageLevel",
        ),
    ]
