# Generated by Django 5.2.4 on 2025-08-02 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0007_remove_primarysubstation_voltage_kv_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProposedConnectionVoltageLevel",
            new_name="ConnectionVoltageLevel",
        ),
    ]
