# Generated by Django 5.2.4 on 2025-08-02 16:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_proposedconnectionvoltagelevel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectionvoltagelevel",
            name="level_kv",
            field=models.DecimalField(
                choices=[
                    (Decimal("6.6"), "6.6 kV"),
                    (Decimal("11"), "11 kV"),
                    (Decimal("25"), "25 kV"),
                    (Decimal("33"), "33 kV"),
                    (Decimal("66"), "66 kV"),
                    (Decimal("132"), "132 kV"),
                    (Decimal("275"), "275 kV"),
                    (Decimal("400"), "400 kV"),
                ],
                decimal_places=1,
                max_digits=5,
            ),
        ),
    ]
