# Generated by Django 5.2.4 on 2025-08-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0014_alter_newconnection_connection_voltage_level_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectionvoltagelevel",
            name="level_kv",
            field=models.CharField(
                choices=[
                    ("6.6", "6.6 kV"),
                    ("11", "11 kV"),
                    ("25", "25 kV"),
                    ("33", "33 kV"),
                    ("66", "66 kV"),
                    ("132", "132 kV"),
                    ("275", "275 kV"),
                    ("400", "400 kV"),
                ],
                max_length=10,
            ),
        ),
    ]
