# Generated by Django 5.2.4 on 2025-08-07 13:18

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_connectionvoltagelevel_level_kv"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newconnection",
            name="bsp_substation",
        ),
        migrations.RemoveField(
            model_name="gspsubstation",
            name="dno_group",
        ),
        migrations.RemoveField(
            model_name="gspsubstation",
            name="voltage_kv",
        ),
        migrations.RemoveField(
            model_name="newconnection",
            name="gsp_substation",
        ),
        migrations.RemoveField(
            model_name="primarysubstation",
            name="dno_group",
        ),
        migrations.RemoveField(
            model_name="primarysubstation",
            name="voltage_kv",
        ),
        migrations.RemoveField(
            model_name="newconnection",
            name="primary_substation",
        ),
        migrations.CreateModel(
            name="Substation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "geolocation",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("gsp", "Grid Supply Point"),
                            ("bsp", "Bulk Supply Point"),
                            ("primary", "Primary"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "dno_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substations",
                        to="core.dnogroup",
                    ),
                ),
                (
                    "voltage_kv",
                    models.ManyToManyField(
                        blank=True,
                        related_name="substations",
                        to="core.connectionvoltagelevel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="newconnection",
            name="substation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="new_connections",
                to="core.substation",
            ),
        ),
        migrations.DeleteModel(
            name="BSPSubstation",
        ),
        migrations.DeleteModel(
            name="GSPSubstation",
        ),
        migrations.DeleteModel(
            name="PrimarySubstation",
        ),
    ]
