# Generated by Django 5.2.4 on 2025-08-30 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_substation_external_identifier_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newconnection",
            name="connection_status",
        ),
        migrations.RemoveField(
            model_name="newconnection",
            name="connection_voltage_level",
        ),
        migrations.RemoveField(
            model_name="substation",
            name="voltage_kv",
        ),
        migrations.RemoveField(
            model_name="newconnection",
            name="dno_group",
        ),
        migrations.RemoveField(
            model_name="newconnection",
            name="reporting_period",
        ),
        migrations.RemoveField(
            model_name="newconnection",
            name="substation",
        ),
        migrations.AlterUniqueTogether(
            name="reportingperiod",
            unique_together=None,
        ),
        migrations.DeleteModel(
            name="ConnectionStatus",
        ),
        migrations.DeleteModel(
            name="ConnectionVoltageLevel",
        ),
        migrations.DeleteModel(
            name="ReportingPeriod",
        ),
        migrations.DeleteModel(
            name="NewConnection",
        ),
    ]
