# Generated by Django 5.2.4 on 2025-09-01 16:07
# Edited by AH on 2025-09-01 16:07 16:09 (original commented out below)

from django.db import migrations

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_substation_unique_dno_group_external_identifier"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE location_input_dnogroup RENAME TO core_dnogroup;",
            reverse_sql="ALTER TABLE core_dnogroup RENAME TO location_input_dnogroup;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE location_input_substation RENAME TO core_substation;",
            reverse_sql="ALTER TABLE core_substation RENAME TO location_input_substation;",
        ),
    ]

# class Migration(migrations.Migration):

#     dependencies = [
#         ("core", "0022_substation_unique_dno_group_external_identifier"),
#     ]

#     operations = [
#         migrations.AlterModelTable(
#             name="dnogroup",
#             table="core_dnogroup",
#         ),
#         migrations.AlterModelTable(
#             name="substation",
#             table="core_substation",
#         ),
#     ]
