# Generated by Django 5.2.4 on 2025-09-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_dnogroup_table_alter_substation_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="dnogroup",
            table="core_dnogroup",
        ),
        migrations.AlterModelTable(
            name="substation",
            table="core_substation",
        ),
    ]
