# Generated by Django 5.2.4 on 2025-07-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Substations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('substation_nged_id', models.IntegerField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('area', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('substationnumber', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('primary', models.TextField(blank=True, null=True)),
                ('bsp', models.TextField(blank=True, null=True)),
                ('gsp', models.TextField(blank=True, null=True)),
                ('demandconnectedheadroommw', models.FloatField(blank=True, null=True)),
                ('demandcontractedheadroommw', models.FloatField(blank=True, null=True)),
                ('demandconnectedrag', models.TextField(blank=True, null=True)),
                ('demandcontractedrag', models.TextField(blank=True, null=True)),
                ('generationtotalcapacity', models.FloatField(blank=True, null=True)),
                ('generationconnectedheadroommw', models.FloatField(blank=True, null=True)),
                ('generationcontractedheadroommw', models.FloatField(blank=True, null=True)),
                ('generationquotedcapacity', models.FloatField(blank=True, null=True)),
                ('generationconnectedrag', models.TextField(blank=True, null=True)),
                ('generationcontractedrag', models.TextField(blank=True, null=True)),
                ('geolocation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'substations',
                'managed': True,
            },
        ),
    ]
