# Generated by Django 5.2.4 on 2025-07-24 15:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_input', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substations',
            name='geolocation',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
