# Generated by Django 5.2.4 on 2025-08-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_input', '0002_remove_dnogroup_abbreviation_dnogroup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnogroup',
            name='name',
        ),
        migrations.AddField(
            model_name='dnogroup',
            name='abbr',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
