# Generated by Django 5.2.4 on 2025-07-30 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_input', '0002_alter_substations_geolocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('budget', 'Budget Estimate Provided'), ('pending', 'Connection Offer – Pending Acceptance'), ('accepted', 'Connection Offer – Accepted')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NewConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_count', models.PositiveIntegerField(blank=True, null=True)),
                ('total_demand_capacity_mw', models.DecimalField(decimal_places=3, help_text='Total demand capacity in megawatts (MW)', max_digits=10)),
                ('generation_count', models.PositiveIntegerField(blank=True, null=True)),
                ('total_generation_capacity_mw', models.DecimalField(decimal_places=3, help_text='Total generation capacity in megawatts (MW)', max_digits=10)),
                ('connection_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_connections', to='location_input.connectionstatus')),
            ],
        ),
        migrations.CreateModel(
            name='ProposedConnectionVoltageLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_kv', models.DecimalField(choices=[(6.6, '6.6 kV'), (11.0, '11 kV'), (33.0, '33 kV'), (66.0, '66 kV'), (132.0, '132 kV')], decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Substations',
        ),
        migrations.AddField(
            model_name='newconnection',
            name='voltage_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_connections', to='location_input.proposedconnectionvoltagelevel'),
        ),
    ]
