# Generated by Django 5.2.4 on 2025-07-31 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_input', '0004_reportingperiod_newconnection_reporting_period'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportingperiod',
            unique_together={('start_date', 'end_date')},
        ),
    ]
