# Generated by Django 5.2.4 on 2025-07-31 08:45

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_input', '0005_alter_reportingperiod_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimarySubstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geolocation', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('data_valid_as_of', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='newconnection',
            name='primary_substation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_connections', to='location_input.primarysubstation'),
        ),
    ]
