# Generated by Django 5.2.4 on 2025-07-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_input', '0006_primarysubstation_newconnection_primary_substation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNOGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(choices=[('UKPN', 'UK Power Networks'), ('NGED', 'National Grid Electricity Distribution'), ('SPEN', 'SP Energy Networks'), ('NP', 'Northern Powergrid'), ('ENW', 'Electricity North West'), ('SSEN', 'Scottish and Southern Electricity Networks')], max_length=10, unique=True)),
            ],
        ),
    ]
