# Generated by Django 5.2.4 on 2025-07-31 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_input', '0007_dnogroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNOLicenceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_area', models.CharField(choices=[('north_west_england', 'North West England'), ('north_east_england', 'North East England'), ('yorkshire', 'Yorkshire'), ('north_scotland', 'North Scotland'), ('southern_england', 'Southern England'), ('merseyside_cheshire_north_wales', 'Merseyside, Cheshire, North Wales'), ('central_southern_scotland', 'Central & Southern Scotland'), ('london', 'London'), ('eastern_england', 'Eastern England'), ('south_east_england', 'South East England'), ('east_midlands', 'East Midlands'), ('west_midlands', 'West Midlands'), ('south_west_england', 'South West England'), ('south_wales', 'South Wales')], max_length=50)),
                ('dno_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licence_areas', to='location_input.dnogroup')),
            ],
        ),
    ]
