# Generated by Django 5.2.4 on 2025-07-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_input', '0008_dnolicencearea'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPublicationDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='primarysubstation',
            name='data_valid_as_of',
        ),
    ]
