# Generated by Django 5.2.4 on 2025-07-31 09:34

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_input', '0009_datapublicationdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BSPSubstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geolocation', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('licence_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bsp_substations', to='location_input.dnolicencearea')),
                ('publication_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bsp_substations', to='location_input.datapublicationdate')),
            ],
        ),
    ]
