# Generated by Django 5.2.4 on 2025-07-31 10:07

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_input', '0011_gspsubstation_delete_bspsubstation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gspsubstation',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='newconnection',
            name='gsp_substation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_connections', to='location_input.gspsubstation'),
        ),
        migrations.CreateModel(
            name='BSPSubstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geolocation', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('gsp_substation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bsp_substations', to='location_input.gspsubstation')),
            ],
        ),
        migrations.AddField(
            model_name='newconnection',
            name='bsp_substation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_connections', to='location_input.bspsubstation'),
        ),
        migrations.AddField(
            model_name='primarysubstation',
            name='bsp_substation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_substations', to='location_input.bspsubstation'),
        ),
    ]
