# Generated by Django 5.2.4 on 2025-07-31 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_input', '0012_remove_gspsubstation_publication_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataPublicationDate',
        ),
    ]
