# Generated by Django 5.2.4 on 2025-07-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_input', '0013_delete_datapublicationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnolicencearea',
            name='licence_area',
            field=models.CharField(choices=[('north_west_england', 'North West England'), ('north_east_england', 'North East England'), ('yorkshire', 'Yorkshire'), ('north_scotland', 'North Scotland'), ('southern_england', 'Southern England'), ('merseyside_cheshire_north_wales', 'Merseyside, Cheshire, North Wales'), ('central_southern_scotland', 'Central & Southern Scotland'), ('london', 'London'), ('eastern_england', 'Eastern England'), ('south_east_england', 'South East England'), ('east_midlands', 'East Midlands'), ('west_midlands', 'West Midlands'), ('south_west', 'South West'), ('south_wales', 'South Wales')], max_length=50),
        ),
    ]
