# Generated by Django 5.2.4 on 2025-07-31 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_input', '0014_alter_dnolicencearea_licence_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bspsubstation',
            name='gsp_substation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bsp_substations', to='location_input.gspsubstation'),
        ),
        migrations.AlterField(
            model_name='primarysubstation',
            name='bsp_substation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_substations', to='location_input.bspsubstation'),
        ),
    ]
