# Generated by Django 5.2.4 on 2025-08-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawDataRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("substations", "Substations"),
                            ("connection_applications", "Connection Applications"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "dno_group",
                    models.CharField(choices=[("nged", "NGED")], max_length=10),
                ),
                (
                    "raw_data",
                    models.TextField(
                        help_text="Raw response data (usually JSON, but can handle other formats like XML, HTML, etc.)"
                    ),
                ),
                ("source_url", models.URLField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
