# Generated by Django 5.2.4 on 2025-08-17 15:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_pipeline", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectionApplicationCleanedDataStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawFetchedDataStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_category",
                    models.CharField(
                        choices=[
                            ("substations", "Substations"),
                            ("connection_applications", "Connection Applications"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "dno_group",
                    models.CharField(choices=[("nged", "NGED")], max_length=255),
                ),
                ("raw_data", models.TextField()),
                ("source_url", models.URLField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubstationCleanedDataStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary Substation"),
                            ("bsp", "Bulk Supply Point"),
                            ("gsp", "Grid Supply Point"),
                        ],
                        max_length=255,
                    ),
                ),
                ("candidate_voltage_levels_kv", models.JSONField(default=list)),
                (
                    "geolocation",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                (
                    "dno_group",
                    models.CharField(choices=[("nged", "NGED")], max_length=255),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="RawDataRecord",
        ),
    ]
