# Generated by Django 5.2.4 on 2025-08-18 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_pipeline", "0002_connectionapplicationcleaneddatastorage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="substationcleaneddatastorage",
            name="raw_data_record",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cleaned_substations",
                to="data_pipeline.rawfetcheddatastorage",
            ),
            preserve_default=False,
        ),
    ]
