# Generated by Django 5.2.4 on 2025-08-18 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_pipeline", "0003_substationcleaneddatastorage_raw_data_record"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rawfetcheddatastorage",
            old_name="raw_data",
            new_name="raw_response",
        ),
    ]
