# Generated by Django 5.2.4 on 2025-08-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_pipeline", "0004_rename_raw_data_rawfetcheddatastorage_raw_response"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rawfetcheddatastorage",
            name="raw_response",
        ),
        migrations.AddField(
            model_name="rawfetcheddatastorage",
            name="response_json",
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
