# Generated by Django 5.2.4 on 2025-08-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_pipeline", "0005_remove_rawfetcheddatastorage_raw_response_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawfetcheddatastorage",
            name="response_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
