# Generated by Django 5.2.4 on 2025-08-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_pipeline", "0006_alter_rawfetcheddatastorage_response_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawfetcheddatastorage",
            name="response_json",
            field=models.JSONField(),
        ),
    ]
