# Generated by Django 5.2.4 on 2025-08-18 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_pipeline", "0007_alter_rawfetcheddatastorage_response_json"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rawfetcheddatastorage",
            old_name="response_json",
            new_name="raw_response_json",
        ),
    ]
