# Generated by Django 5.2.4 on 2025-08-19 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_pipeline",
            "0008_rename_response_json_rawfetcheddatastorage_raw_response_json",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="rawfetcheddatastorage",
            old_name="raw_response_json",
            new_name="raw_payload_json",
        ),
    ]
