# Generated by Django 5.2.4 on 2025-08-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_pipeline",
            "0009_rename_raw_response_json_rawfetcheddatastorage_raw_payload_json",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawfetcheddatastorage",
            name="data_category",
            field=models.CharField(
                choices=[
                    ("substation", "Substations"),
                    ("connection_application", "Connection Applications"),
                ],
                max_length=255,
            ),
        ),
    ]
