# Generated by Django 5.2.4 on 2025-08-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_pipeline", "0010_alter_rawfetcheddatastorage_data_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="substationcleaneddatastorage",
            name="external_identifier",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
