# Generated by Django 5.2.4 on 2025-08-19 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_pipeline", "0011_substationcleaneddatastorage_external_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="substationcleaneddatastorage",
            name="reference",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="substationcleaneddatastorage",
            name="raw_data_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cleaned_substations",
                to="data_pipeline.rawfetcheddatastorage",
            ),
        ),
    ]
