# Generated by Django 5.2.4 on 2025-08-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_pipeline", "0012_substationcleaneddatastorage_reference_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="substationcleaneddatastorage",
            name="raw_data_record",
        ),
    ]
