# Generated by Django 5.2.4 on 2025-08-20 10:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_pipeline", "0013_remove_substationcleaneddatastorage_raw_data_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawfetcheddatastorage",
            name="reference",
            field=models.CharField(default="nged_substation", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="substationcleaneddatastorage",
            name="cleaned_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="substationcleaneddatastorage",
            name="reference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
