# Generated by Django 5.2.4 on 2025-08-20 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_pipeline", "0014_rawfetcheddatastorage_reference_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="substationcleaneddatastorage",
            old_name="cleaned_at",
            new_name="prepared_at",
        ),
    ]
