# Generated by Django 5.2.4 on 2025-08-20 16:30

import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_pipeline",
            "0015_rename_cleaned_at_substationcleaneddatastorage_prepared_at",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="connectionapplicationcleaneddatastorage",
            name="candidate_voltage_levels_kv",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="connectionapplicationcleaneddatastorage",
            name="connection_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("budget", "Budget"),
                    ("accepted", "Accepted"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="connectionapplicationcleaneddatastorage",
            name="dno_group",
            field=models.CharField(
                choices=[("nged", "NGED")], default="nged", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="connectionapplicationcleaneddatastorage",
            name="external_identifier",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="connectionapplicationcleaneddatastorage",
            name="geolocation",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="connectionapplicationcleaneddatastorage",
            name="name",
            field=models.CharField(default="Warwick", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="connectionapplicationcleaneddatastorage",
            name="prepared_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="connectionapplicationcleaneddatastorage",
            name="proposed_voltage",
            field=models.DecimalField(decimal_places=1, default=6.6, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="connectionapplicationcleaneddatastorage",
            name="reference",
            field=models.CharField(default="Warwick", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="connectionapplicationcleaneddatastorage",
            name="total_demand_capacity_mw",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="connectionapplicationcleaneddatastorage",
            name="total_demand_number",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="connectionapplicationcleaneddatastorage",
            name="total_generation_capacity_mw",
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="connectionapplicationcleaneddatastorage",
            name="total_generation_number",
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="connectionapplicationcleaneddatastorage",
            name="type",
            field=models.CharField(
                choices=[
                    ("primary", "Primary Substation"),
                    ("bsp", "Bulk Supply Point"),
                    ("gsp", "Grid Supply Point"),
                ],
                default="primary",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="substationcleaneddatastorage",
            name="prepared_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="substationcleaneddatastorage",
            name="reference",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
