# Generated by Django 5.2.4 on 2025-08-21 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_pipeline",
            "0016_connectionapplicationcleaneddatastorage_candidate_voltage_levels_kv_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="connectionapplicationcleaneddatastorage",
            old_name="type",
            new_name="substation_type",
        ),
    ]
