# Generated by Django 5.2.4 on 2025-08-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_pipeline",
            "0017_rename_type_connectionapplicationcleaneddatastorage_substation_type",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectionapplicationcleaneddatastorage",
            name="dno_group",
            field=models.CharField(
                choices=[("nged", "NGED"), ("ukpn", "UKPN")], max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="rawfetcheddatastorage",
            name="dno_group",
            field=models.CharField(
                choices=[("nged", "NGED"), ("ukpn", "UKPN")], max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="substationcleaneddatastorage",
            name="dno_group",
            field=models.CharField(
                choices=[("nged", "NGED"), ("ukpn", "UKPN")], max_length=255
            ),
        ),
    ]
