# Generated by Django 5.2.4 on 2025-09-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_pipeline",
            "0018_alter_connectionapplicationcleaneddatastorage_dno_group_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectionapplicationcleaneddatastorage",
            name="dno_group",
            field=models.CharField(
                choices=[("nged", "NGED"), ("ukpn", "UKPN"), ("np", "NP")],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="rawfetcheddatastorage",
            name="dno_group",
            field=models.CharField(
                choices=[("nged", "NGED"), ("ukpn", "UKPN"), ("np", "NP")],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="substationcleaneddatastorage",
            name="dno_group",
            field=models.CharField(
                choices=[("nged", "NGED"), ("ukpn", "UKPN"), ("np", "NP")],
                max_length=255,
            ),
        ),
    ]
